# Using Numpy program to solve problems

## Problem Statement

* 1) Write a NumPy program to get help on the add function.
* 2) Write a NumPy program to create an array with values ranging from 12 to 38.
* 3) Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.
* 4) Write a NumPy program to create a 2d array with 1 on the border and 0 inside.
* 5) Write a NumPy program to append values to the end of an array.
* 6) Write a NumPy program to generate five random numbers from the normal distribution.
* 7) Write a NumPy program to get the n largest values of an array.

####  1) Write a NumPy program to get help on the add function.

In [2]:
import numpy as np
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 2) Write a NumPy program to create an array with values ranging from 12 to 38.

In [3]:
np.arange(12,38)

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37])

#### 3) Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.

In [11]:
values =np.array([[[2,3,4],[5,6,7],[8,9,10]]])
print(values)

values.reshape((3,3))



[[[ 2  3  4]
  [ 5  6  7]
  [ 8  9 10]]]


array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

#### 4) Write a NumPy program to create a 2d array with 1 on the border and 0 inside.

In [12]:
n = 5

import numpy as np

border = np.ones((n, n), dtype = int)
border[1:-1, 1:-1] = 0
print(border)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


np.ones((5,5))

#### 5) Write a NumPy program to append values to the end of an array.

In [20]:
arr = np.array([1,2,3,4])
print('original array: ', arr)

app_arr = np.append(arr, [5,6])
print('appended array: ', app_arr)

original array:  [1 2 3 4]
appended array:  [1 2 3 4 5 6]


#### 6) Write a NumPy program to generate five random numbers from the normal distribution.

In [23]:
a = np.random.normal(size=5)
print(a)

[ 0.34466964 -1.56746851 -0.34762081 -0.56145353  1.10089729]


####  7) Write a NumPy program to get the n largest values of an array.

In [30]:
x = np.array([2,3,5,6,4,12,14,9])
print('Given array: ', x)

sorted_index_array = np.argsort(x)

sorted_array = x[sorted_index_array]

print('Sorted array: ', sorted_array)

n=1
result = sorted_array[-n:]
print('{} largest number is,'.format(n),result)

Given array:  [ 2  3  5  6  4 12 14  9]
Sorted array:  [ 2  3  4  5  6  9 12 14]
1 largest number is, [14]
